### ISSUE TITLE
Unable to find a specification for `TwilioChatClient`

### ISSUE THREAD

**Issue by otymartin** [TwilioDevEd/twiliochat-swift#11]
@joliveros 
```swift
[!] Unable to find a specification for `TwilioChatClient (~> 0.16.0)`
[!] Unable to find a specification for `TwilioAccessManager (~> 0.1.1)`

**Comment by joliveros** [comment]
Hi @otymartin,

It seems you may have a problem with your pods repo. I would try either one of these solutions:
```bash
pod repo remove master
pod setup
pod install
```

Or:

```bash
sudo rm -fr ~/.cocoapods/repos/master
pod setup
pod install
```

**Comment by otymartin** [comment]
whats the difference between `TwilioChatClient, TwilioAccessManager` and `TwilioCommon, TwilioIPMessagingClient`?

**Comment by joliveros** [comment]
You can see more info regarding the refactor of the SDK here:
https://www.twilio.com/docs/api/chat/guides/migration-guide-ios-0160

**Comment by otymartin** [comment]
@joliveros  i tried both methods but nothing works

It only worked when I specified the source at the top of my podfile, how come?

```swift
source 'https://github.com/CocoaPods/Specs'
source 'https://github.com/twilio/cocoapod-specs'

**Comment by joliveros** [comment]
That's definitely a sign that something is wrong with cocoapods setup. I would clear my config and install cocoapods again:

One way to clear caches:
https://gist.github.com/mbinna/4202236

Re-install cocoapods:
```bash
gem install cocoapods
```

**Comment by mcelicalderon** [comment]
@otymartin Those source lines are necessary and currently in the Podfile. If you don't specify a source, cocoapods will try to use `https://github.com/twilio/cocoapod-specs`. But as we need to specify Twilio's source, you also need to explicitly tell cocoapods to search in `https://github.com/twilio/cocoapod-specs`
