### ISSUE TITLE
Delegate method "ChannelAdded" not called

### ISSUE THREAD

**Issue by otymartin** [TwilioDevEd/twiliochat-swift#14]
I can see logs in my xcode debug area whenever I successful invite a user but the delegate method recieves no callback. My implementation is the same as the example in this repo.. whats wrong?

```swift
extension MessagingManager: TwilioChatClientDelegate {
    
    func chatClient(_ client: TwilioChatClient!, channelAdded channel: TCHChannel!) {
        print("****CHANNEL ADDED")
        if channel.status == .invited {
            print("****invited wooooo")
        }
        self.delegate?.chatClient(client, channelAdded: channel)
    }

**Comment by jefflinwood** [comment]
Hi,

Was the issue that you don't see the print statements, or that the delegate on the MessagingManager never gets called?

Thanks!
Jeff

**Comment by otymartin** [comment]
@jefflinwood 
the delegate wasnt called. problem was my synchronization stategy. only the `all` sync strategy will monitor channel events such as channel added. the `channel list` strategy doesnt do that

**Comment by otymartin** [comment]
This is now Fixed. The updated `channelList` sync strategy will now listen for `channelAdded` event.
