### ISSUE TITLE
Error(Typo) in TokenRequestHandler fetchToken function

### ISSUE THREAD

**Issue by JaiDeves** [TwilioDevEd/twiliochat-swift#33]
Please update your **postDataFrom** function, 
currenty the line `data = encodedKey + "=" + encodedValue;` is adding only the last param, but it should append all the parameters.

So change that line to `data += encodedKey + "=" + encodedValue;`

I was not able to connect because of the above small typo, getting error "Error validating token, code=102 ".
After changing that line, app's working fine.

**Comment by jefflinwood** [comment]
Hi,

Thanks for the bug report! I'll take a look at this and make the fix.

**Comment by jefflinwood** [comment]
Fixed in https://github.com/TwilioDevEd/twiliochat-swift/pull/34 - thanks again!
