### ISSUE TITLE
textView MainChatViewController is not tapped

### ISSUE THREAD

**Issue by ShaikBaji1506** [TwilioDevEd/twiliochat-swift#37]
when I put the same class of MainChatViewController for chat textview of chat not tapped I am getting error Reading from public effective user settings.

**Comment by NaiyerAghaz** [comment]
I also getting this error please help me out.

**Comment by NaiyerAghaz** [comment]
The issue has resolved now, problem was that , MainChatViewController is not pushed properly I was presenting from navigation controller that why is not working now  I push controller then work it.
